CREATE TABLE IF NOT EXISTS company_phone (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  company_id INTEGER NOT NULL REFERENCES company(id) ON DELETE CASCADE,
  label      TEXT,
  phone      TEXT NOT NULL,
  is_primary INTEGER NOT NULL DEFAULT 0
);
